# Generated by Django 5.2.14 on 2026-05-13 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="listings.listing",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        limit_choices_to={"role": "renter"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("listing", "renter")},
            },
        ),
    ]
