# Generated by Django 5.2.14 on 2026-05-22 07:27

import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_manage_leases_permission"),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="landlord",
            field=models.ForeignKey(
                limit_choices_to=listings.models._lease_manager_profiles_q,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="accounts.profile",
            ),
        ),
    ]
