# Generated by Django 5.2.14 on 2026-05-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_listing_landlord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "amenities",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="listing",
            name="address",
        ),
        migrations.RemoveField(
            model_name="listingimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="listingimage",
            name="is_primary",
        ),
        migrations.AddField(
            model_name="listing",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="listing",
            name="hero_image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="listing",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="caption",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="image_url",
            field=models.URLField(default="https://example.com/default.jpg"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="listings", to="listings.amenity"
            ),
        ),
    ]
