# Generated by Django 5.2.14 on 2026-05-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_amenity_remove_listing_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="listing_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entire_place", "Entire Place"),
                    ("private_room", "Private Room"),
                    ("shared_room", "Shared Room"),
                    ("bedspace", "Bedspace"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "Apartment"),
                    ("condominium", "Condominium"),
                    ("house", "House"),
                    ("townhouse", "Townhouse"),
                    ("studio", "Studio"),
                    ("dorm", "Dormitory"),
                    ("office", "Office"),
                    ("commercial", "Commercial"),
                    ("lot", "Lot/Land"),
                ],
                max_length=30,
            ),
        ),
    ]
