# Generated by Django 5.2.14 on 2026-05-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_listing_type_listing_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
