# Generated by Django 5.2.14 on 2026-05-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_listing_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="bedrooms",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
