# Generated by Django 5.2.14 on 2026-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_alter_listing_bedrooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=None, max_digits=2, null=True
            ),
        ),
    ]
