# Generated by Django 5.2.14 on 2026-06-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_listing_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="city_google_place_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
