# Generated by Django 5.2.14 on 2026-06-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_listing_city_google_place_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_furnished",
            field=models.BooleanField(default=True),
        ),
    ]
