# Generated by Django 5.2.14 on 2026-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_listing_is_furnished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="is_furnished",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
