# Generated by Django 5.2.14 on 2026-06-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_alter_listing_is_furnished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="hero_image",
            field=models.URLField(
                blank=True,
                default="https://res.cloudinary.com/braveheartimages/image/upload/v1782165141/eioh6ottrzthsla6unjw.jpg",
            ),
        ),
    ]
