# Generated by Django 5.2.14 on 2026-06-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_alter_listing_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_unfinished",
            field=models.BooleanField(default=True),
        ),
    ]
