# Generated by Django 5.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("landlord", "Landlord"), ("renter", "Renter")],
                max_length=10,
                null=True,
            ),
        ),
    ]
