# Generated by Django 5.2.14

from django.db import migrations, models


def copy_landlord_role_to_flag(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.filter(role="landlord").update(leasing_host=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="leasing_host",
            field=models.BooleanField(
                default=False,
                help_text="Optional upgrade: user may create and manage lease listings.",
            ),
        ),
        migrations.RunPython(copy_landlord_role_to_flag, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="profile",
            name="role",
        ),
    ]
