# Generated by Django 5.2.14

from django.db import migrations


def copy_leasing_host_to_permission(apps, schema_editor):
    """
    Grant ``manage_leases`` explicitly: custom permission rows are normally
    created in post_migrate (after this migration batch), so we ensure it exists.
    """
    Profile = apps.get_model("accounts", "Profile")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    ct, _ = ContentType.objects.get_or_create(
        app_label="accounts",
        model="profile",
    )
    perm, _ = Permission.objects.get_or_create(
        content_type=ct,
        codename="manage_leases",
        defaults={"name": "Can create and manage lease listings"},
    )

    for profile in Profile.objects.filter(leasing_host=True).iterator():
        profile.user.user_permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_leasing_host"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": [
                    ("manage_leases", "Can create and manage lease listings"),
                ],
            },
        ),
        migrations.RunPython(copy_leasing_host_to_permission, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="profile",
            name="leasing_host",
        ),
    ]
