# Generated by Django 5.2.14 on 2026-06-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_manage_leases_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
