# Generated by Django 5.2.14 on 2026-06-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_profile_avatar_remove_profile_bio_and_more"),
        ("listings", "0012_listing_is_unfinished"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="liked_listings",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="listings.listing"
            ),
        ),
    ]
